# Docker Compose override for fast deployments using pre-built base images
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.fast
      args:
        BASE_IMAGE: ghcr.io/${GITHUB_REPOSITORY_OWNER:-your-org}/claude-workflow-backend-base:${BASE_IMAGE_TAG:-latest}
    image: claude-backend:fast

  claude-terminal:
    build:
      context: ./backend
      dockerfile: Dockerfile.terminal.fast
      args:
        BASE_IMAGE: ghcr.io/${GITHUB_REPOSITORY_OWNER:-your-org}/claude-workflow-terminal-base:${BASE_IMAGE_TAG:-latest}
    image: claude-terminal:fast

  mcp-server:
    build:
      context: ./backend
      dockerfile: Dockerfile.mcp
    image: claude-mcp:fast

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.fast
      args:
        BASE_IMAGE: ghcr.io/${GITHUB_REPOSITORY_OWNER:-your-org}/claude-workflow-frontend-base:${BASE_IMAGE_TAG:-latest}
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8005}
        REACT_APP_WS_URL: ${REACT_APP_WS_URL:-ws://localhost:8005}
        REACT_APP_API_PORT: ${REACT_APP_API_PORT:-8005}
        REACT_APP_WS_PORT: ${REACT_APP_WS_PORT:-8006}
        REACT_APP_VOICE_API_URL: ${REACT_APP_VOICE_API_URL:-http://localhost:14300}
    image: claude-frontend:fast
