# Docker Compose override for faster builds with cache
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - python:3.11-slim
      target: final
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: claude-backend:cache

  claude-terminal:
    build:
      context: ./backend
      dockerfile: Dockerfile.terminal
      cache_from:
        - python:3.11-slim
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: claude-terminal:cache

  mcp-server:
    build:
      context: ./backend
      dockerfile: Dockerfile.mcp
      cache_from:
        - python:3.11-slim
      target: final
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: claude-mcp:cache

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: claude-frontend:cache
